import "server-only";
import { randomUUID } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, open, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { del, get, put } from "@vercel/blob";

/**
 * PRIVATE storage for applicant documents (passports, bank statements, ...).
 *
 *  - Production: a Vercel Blob *private* store, configured via PRIVATE_BLOB_READ_WRITE_TOKEN
 *    (falls back to BLOB_READ_WRITE_TOKEN, which is what Vercel injects when a store is connected).
 *    If that token belonged to a public store, writes with access "private" would fail rather than leak.
 *    Objects have no public URL; bytes are only ever streamed through our authorised
 *    download route (src/app/api/documents/[id]/route.ts).
 *  - Development/tests only: the local filesystem under PRIVATE_STORAGE_DIR (default
 *    `.data/private-documents`, git-ignored, and NEVER inside /public).
 *
 * Keys are generated by the server (never derived from user input).
 */
export interface StoredObject {
  stream: ReadableStream<Uint8Array>;
  contentType: string;
  size: number;
}

export interface StoredHead {
  size: number;
  /** First bytes of the object (enough for a magic-number check). */
  head: Buffer;
}

export interface PrivateStorage {
  /** "blob": browsers upload directly with a server-issued token. "local": browsers send bytes to our own route (dev/tests). */
  readonly mode: "blob" | "local";
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  /** Size and first bytes of a stored object, or null if it doesn't exist. */
  inspect(key: string): Promise<StoredHead | null>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

const DOCUMENT_KEY_RE = /^applications\/[a-z0-9]+\/[a-f0-9-]{36}\.(pdf|jpg|png)$/;
/** Public marketing images (package artwork) share the store but live under their own prefix. */
const MESSAGE_KEY_RE = /^messages\/[a-z0-9]+\/[a-f0-9-]{36}\.(pdf|jpg|png)$/;
const PAYMENT_PROOF_KEY_RE = /^payments\/[a-z0-9]+\/[a-f0-9-]{36}\.(pdf|jpg|png)$/;
export const PACKAGE_IMAGE_KEY_RE = /^package-images\/[a-f0-9-]{36}\.(jpg|png|webp)$/;

function assertKey(key: string) {
  if (!DOCUMENT_KEY_RE.test(key) && !PAYMENT_PROOF_KEY_RE.test(key) && !MESSAGE_KEY_RE.test(key) && !PACKAGE_IMAGE_KEY_RE.test(key)) throw new Error("Invalid storage key");
}

/** Whether a key is one the server may issue for client uploads (never package artwork). */
export function isClientUploadKey(key: string): boolean {
  return DOCUMENT_KEY_RE.test(key) || PAYMENT_PROOF_KEY_RE.test(key) || MESSAGE_KEY_RE.test(key);
}

async function readHead(stream: ReadableStream<Uint8Array>, n: number): Promise<Buffer> {
  const reader = stream.getReader();
  const chunks: Buffer[] = [];
  let have = 0;
  try {
    while (have < n) {
      const { done, value } = await reader.read();
      if (done) break;
      chunks.push(Buffer.from(value));
      have += value.length;
    }
  } finally {
    await reader.cancel().catch(() => undefined);
  }
  return Buffer.concat(chunks).subarray(0, n);
}

export function privateBlobToken(): string | undefined {
  return process.env.PRIVATE_BLOB_READ_WRITE_TOKEN || process.env.BLOB_READ_WRITE_TOKEN || undefined;
}

class VercelPrivateStorage implements PrivateStorage {
  readonly mode = "blob" as const;
  constructor(private readonly token: string) {}
  async inspect(key: string) {
    assertKey(key);
    const res = await get(key, { access: "private", token: this.token, useCache: false });
    if (!res || res.statusCode !== 200) return null;
    return { size: res.blob.size, head: await readHead(res.stream, 16) };
  }
  async put(key: string, bytes: Buffer, contentType: string) {
    assertKey(key);
    await put(key, bytes, { access: "private", token: this.token, contentType, addRandomSuffix: false, allowOverwrite: false });
  }
  async get(key: string) {
    assertKey(key);
    const res = await get(key, { access: "private", token: this.token, useCache: false });
    if (!res || res.statusCode !== 200) return null;
    return { stream: res.stream, contentType: res.blob.contentType, size: res.blob.size };
  }
  async delete(key: string) {
    assertKey(key);
    await del(key, { token: this.token });
  }
}

class LocalPrivateStorage implements PrivateStorage {
  readonly mode = "local" as const;
  constructor(private readonly root: string) {}
  async inspect(key: string) {
    const f = this.file(key);
    try {
      const s = await stat(f);
      const fh = await open(f, "r");
      try {
        const buf = Buffer.alloc(Math.min(16, s.size));
        await fh.read(buf, 0, buf.length, 0);
        return { size: s.size, head: buf };
      } finally {
        await fh.close();
      }
    } catch {
      return null;
    }
  }
  private file(key: string) {
    assertKey(key);
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error("Invalid storage key");
    return full;
  }
  async put(key: string, bytes: Buffer) {
    const f = this.file(key);
    await mkdir(path.dirname(f), { recursive: true });
    await writeFile(f, bytes, { flag: "wx" });
  }
  async get(key: string) {
    const f = this.file(key);
    try {
      const s = await stat(f);
      const ext = path.extname(f).slice(1);
      const contentType = ext === "pdf" ? "application/pdf" : ext === "png" ? "image/png" : ext === "webp" ? "image/webp" : "image/jpeg";
      return { stream: Readable.toWeb(createReadStream(f)) as ReadableStream<Uint8Array>, contentType, size: s.size };
    } catch {
      return null;
    }
  }
  async delete(key: string) {
    await rm(this.file(key), { force: true });
  }
  /** Test helper. */
  async read(key: string) {
    return readFile(this.file(key));
  }
}

/** Server-generated key for a bank-transfer proof. */
export function newPaymentProofKey(paymentId: string, format: "pdf" | "jpg" | "png"): string {
  return `payments/${paymentId}/${randomUUID()}.${format}`;
}

let instance: PrivateStorage | undefined;

export function getPrivateStorage(): PrivateStorage {
  if (instance) return instance;
  const token = process.env.PRIVATE_BLOB_READ_WRITE_TOKEN || process.env.BLOB_READ_WRITE_TOKEN;
  if (token) return (instance = new VercelPrivateStorage(token));
  if (process.env.NODE_ENV === "production" && !process.env.ALLOW_LOCAL_PRIVATE_STORAGE) {
    throw new Error("Private storage is not configured (set BLOB_READ_WRITE_TOKEN or PRIVATE_BLOB_READ_WRITE_TOKEN).");
  }
  return (instance = new LocalPrivateStorage(path.resolve(/*turbopackIgnore: true*/ process.env.PRIVATE_STORAGE_DIR ?? ".data/private-documents")));
}

/** Test seam. */
export function setPrivateStorageForTests(storage: PrivateStorage | undefined) {
  instance = storage;
}
