import "server-only";
import { createReadStream } from "node:fs";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { del, get, put } from "@vercel/blob";

/**
 * PRIVATE storage for applicant documents (passports, bank statements, ...).
 *
 *  - Production: a Vercel Blob *private* store, configured via PRIVATE_BLOB_READ_WRITE_TOKEN.
 *    Objects have no public URL; bytes are only ever streamed through our authorised
 *    download route (src/app/api/documents/[id]/route.ts).
 *  - Development/tests only: the local filesystem under PRIVATE_STORAGE_DIR (default
 *    `.data/private-documents`, git-ignored, and NEVER inside /public).
 *
 * Keys are generated by the server (never derived from user input).
 */
export interface StoredObject {
  stream: ReadableStream<Uint8Array>;
  contentType: string;
  size: number;
}

export interface PrivateStorage {
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

const KEY_RE = /^applications\/[a-z0-9]+\/[a-f0-9-]{36}\.(pdf|jpg|png)$/;

function assertKey(key: string) {
  if (!KEY_RE.test(key)) throw new Error("Invalid storage key");
}

class VercelPrivateStorage implements PrivateStorage {
  constructor(private readonly token: string) {}
  async put(key: string, bytes: Buffer, contentType: string) {
    assertKey(key);
    await put(key, bytes, { access: "private", token: this.token, contentType, addRandomSuffix: false, allowOverwrite: false });
  }
  async get(key: string) {
    assertKey(key);
    const res = await get(key, { access: "private", token: this.token, useCache: false });
    if (!res || res.statusCode !== 200) return null;
    return { stream: res.stream, contentType: res.blob.contentType, size: res.blob.size };
  }
  async delete(key: string) {
    assertKey(key);
    await del(key, { token: this.token });
  }
}

class LocalPrivateStorage implements PrivateStorage {
  constructor(private readonly root: string) {}
  private file(key: string) {
    assertKey(key);
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error("Invalid storage key");
    return full;
  }
  async put(key: string, bytes: Buffer) {
    const f = this.file(key);
    await mkdir(path.dirname(f), { recursive: true });
    await writeFile(f, bytes, { flag: "wx" });
  }
  async get(key: string) {
    const f = this.file(key);
    try {
      const s = await stat(f);
      const ext = path.extname(f).slice(1);
      const contentType = ext === "pdf" ? "application/pdf" : ext === "png" ? "image/png" : "image/jpeg";
      return { stream: Readable.toWeb(createReadStream(f)) as ReadableStream<Uint8Array>, contentType, size: s.size };
    } catch {
      return null;
    }
  }
  async delete(key: string) {
    await rm(this.file(key), { force: true });
  }
  /** Test helper. */
  async read(key: string) {
    return readFile(this.file(key));
  }
}

let instance: PrivateStorage | undefined;

export function getPrivateStorage(): PrivateStorage {
  if (instance) return instance;
  const token = process.env.PRIVATE_BLOB_READ_WRITE_TOKEN;
  if (token) return (instance = new VercelPrivateStorage(token));
  if (process.env.NODE_ENV === "production" && !process.env.ALLOW_LOCAL_PRIVATE_STORAGE) {
    throw new Error("Private document storage is not configured (PRIVATE_BLOB_READ_WRITE_TOKEN).");
  }
  return (instance = new LocalPrivateStorage(path.resolve(process.env.PRIVATE_STORAGE_DIR ?? ".data/private-documents")));
}

/** Test seam. */
export function setPrivateStorageForTests(storage: PrivateStorage | undefined) {
  instance = storage;
}
